# Lang
language: en

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Archives: /archives
  #Programming: /programming
  #Categories: /categories
  Resume: /resume
  About: /about
  Blog: /blog
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics: UA-102765380-1
favicon: /images/squirrel.png
twitter:
google_plus: 
fb_admins:
fb_app_id:


# Profile
nickname: Smart Ni
description: I am a Android developer, student and lifelong learner interested in everything. 


links:
  Blog: /archives
  GitHub: https://github.com/SmartNJ
  #Instagram: http://instagram.com/
  #Facebook: http://facebook.com/
  #Twitter : http://twitter.com/


# Info
archive_footer_content: It's not about making one choice and being done with it. It's about continuous learning and sometimes, bold choices. 

post_footer_content: It's not about making one choice and being done with it. It's about continuous learning and sometimes, bold choices. 
